---
title: "Appendix: Source code"
output:
  pdf_document:
    latex_engine: pdflatex
    keep_tex: true
  html_document:
    df_print: paged
date: "2024-05-26"
---

```{r setup, include=TRUE, echo=TRUE}
knitr::opts_chunk$set(echo = TRUE)
rm(list = ls())
gc()
set.seed(1)
options(digits=5) 
if (!require("pacman")) install.packages("pacman")
pacman::p_load(
  plm,
  ggplot2,
  tidyverse,
  fixest,
  knitr,
  kableExtra,
  tidymodels,
  modelsummary,
  ggplot2,
  skimr
)
```

### Data
```{r echo=TRUE, include=TRUE}

orig_df <- read_csv("./input/WSDR.csv")
head(orig_df, 30)
```


## Answer to Q1
```{r echo=TRUE, include=TRUE}
### Q1 Answer ###
stats <- orig_df %>%
  dplyr::select(move,price, profit, custcoun) %>%
  skimr::skim(.) %>%
  skimr::yank("numeric") %>%
  dplyr::select(skim_variable, mean, sd, p0, p100) %>%
  dplyr::mutate_at(vars(mean, sd, p0, p100), ~round(., 3)) %>%
  kable(format = "latex")
cat(stats)
```

## Answer to Q2
```{r echo=TRUE, include=TRUE}
### Q2 Answer ###

# to factor
df <- orig_df |>
  mutate(upc = factor(upc)) |>
  arrange(week, store, upc)

# create product dummy cols
dummy_vars <- model.matrix(~ upc - 1, data = df)
colnames(dummy_vars) <- gsub("upc", "dummy_", colnames(dummy_vars))
df <- cbind(df, dummy_vars)
# delete reference of dummy col
df <- df |>  select(-c(dummy_1200000230)) 

# compute market share
df <- df |>
  dplyr::group_by(store, week) |>
  mutate(M_t = mean(custcoun),
         tot_quant_t = sum(move),
         s_jt = move / M_t,
         s_0t = (M_t- tot_quant_t) / M_t,
         logit_share = log(s_jt/s_0t)) |>
  ungroup() |>
  select(-c(M_t, tot_quant_t))

# compute iV
df <- df |>
  mutate(whole_p_jt = price * (1 - profit*(0.01)))

# OLS estimation in Berry's logit
model1_OLS <- feols(logit_share ~  price + i(upc), 
               df, vcov="hetero"
)

# IV estimation in Berry's logit
model1_IV <- feols(logit_share ~  i(upc) | price ~ whole_p_jt, 
               df, vcov="hetero"
)

# First stage
etable(model1_IV, stage = 1, fitstat=~ . + ivfall + ivwaldall.p,
       signif.code=c("***"=0.01,"**"=0.05,"*"=0.10), 
       style.tex = style.tex("aer"),  tex = TRUE,
       digits=3, digits.stats=3)

# Estimation result
etable(model1_OLS, model1_IV, stage = 2, fitstat=~ . + ivfall + ivwaldall.p,
       signif.code=c("***"=0.01,"**"=0.05,"*"=0.10), 
       style.tex = style.tex("aer"),  tex = TRUE,
       digits=3, digits.stats=3)
```

## Answer to Q4
```{r echo=TRUE, include=TRUE}
### Q4 Answer ###

# compute own elasticity for each market
own_elas_jt <- df |>
  select(week, store, upc, descrip, price, move, s_jt, Brand) |>
  mutate(own_elas = model1_IV$coefficients["fit_price"] * price * (1 - s_jt)) 

# take median of own elasticity by upc
own_elas_df <- own_elas_jt |>
  select(upc, descrip, own_elas) |>
  group_by(upc, descrip) |>
  summarize(own_elas = median(own_elas), .groups = 'drop')

# compute cross elasticity for each market
cross_elas_jt <- df |>
  select(week, store, upc, descrip, price, move, s_jt, Brand) |>
  mutate(cross_elas = (-1) * model1_IV$coefficients["fit_price"] * price * s_jt)
  
# take median of cross elasticity by upc
cross_elas_df <- cross_elas_jt |>
  select(upc, descrip, cross_elas) |>
  group_by(upc, descrip) |>
  summarize(cross_elas = median(cross_elas), .groups = 'drop')

# create elasticity matrix
J <- nrow(cross_elas_df)
elas_mat_med <- matrix( rep(cross_elas_df$cross_elas, J), nrow = J, ncol = J)
diag(elas_mat_med) <- own_elas_df$own_elas
colnames(elas_mat_med) <- rownames(elas_mat_med) <- as.character(cross_elas_df$descrip)
res_elas_mat <- elas_mat_med |>
  knitr::kable(format = "latex", booktabs = TRUE, caption = "Median Elasticity matrix") |>
  kableExtra::kable_styling(latex_options = "hold_position")
cat(res_elas_mat)
```

## Setup function for Q5 & Q6
```{r echo=TRUE, include=TRUE}
# compute markup and marginal cost
compute_markup <- function(own_elas_jt, closs_elas_jt,  owner_mat, is_Multi=FALSE) {
  
  unique_week <- unique(own_elas_jt$week)
  unique_store <- unique(own_elas_jt$store)
  
  market_comb <- expand.grid(week = unique_week, store = unique_store)
  
  # store list of markup and mc
  markup_mc_list <- vector("list", nrow(market_comb))
  
  # calc markup and mc for each market
  for (i in 1:nrow(market_comb)) {
    
    week_i <- market_comb$week[i]
    store_i <- market_comb$store[i]
    
    # subset of a particular market
    sub_own_elas <- own_elas_jt |> filter(week == week_i & store == store_i)
    sub_cross_elas <- cross_elas_jt |> filter(week == week_i & store == store_i)
    
    # number of product
    J <- nrow(sub_cross_elas)
    
    # if multi-product bertrand nash
    if (is_Multi) {
      for (j in 1:J) {
        for (k in 1:J) {
          # if j's brand is equal to k's brand, take 1 
          if (sub_cross_elas$Brand[j] == sub_cross_elas$Brand[k]){
            owner_mat[j,k] = 1
          }
        }
      }
    }
    
    # calculate elasticity matrix
    elas_mat <- matrix(rep(sub_cross_elas$cross_elas, J), nrow = J, ncol = J)
    diag(elas_mat) <- sub_own_elas$own_elas
    
    # calculate matrix S(p)
    price_mat <- matrix(rep((1/sub_cross_elas$price), J), nrow = J, ncol = J)
    share_mat <- t(matrix(rep(sub_cross_elas$s_jt, J), nrow = J, ncol = J))
    S_p_mat <- (-1) * elas_mat * price_mat * share_mat
    
    # calculate markup for a paticular market
    D_p_mat <- owner_mat * S_p_mat
    markup <- solve(D_p_mat) %*% sub_cross_elas$s_jt
    mc <- sub_cross_elas$price - markup
    
    return_df <- data.frame(week = market_comb$week[i],
                            store = market_comb$store[i],
                            Brand = sub_cross_elas$Brand, 
                            upc = sub_cross_elas$upc, 
                            descrip = sub_cross_elas$descrip, 
                            price = sub_cross_elas$price, 
                            move = sub_cross_elas$move, 
                            markup = markup, 
                            mc = mc) %>%
      mutate(markup_dev_p = markup/price)
    
    markup_mc_list[[i]] <- return_df
  }
  
  result_df <- do.call(rbind, markup_mc_list)
  return(result_df)
} 
```

## Answer to Q5
```{r echo=TRUE, include=TRUE}
### Q5 Answer ###

# compute single product Nash equilibrium for each market
J <- nrow(cross_elas_df)
Omega_sin <- diag(J)
markup_sin <- compute_markup(own_elas_jt, cross_elas_jt, Omega_sin)
markup_sin_med <- markup_sin |>
  select(Brand, descrip, markup, markup_dev_p, mc) |>
  group_by(Brand, descrip) |>
  summarize(markup = median(markup), markup_dev_p = median(markup_dev_p), 
            mc = median(mc), .groups = 'drop')

# compute multi product Nash equilibrium for each market
Omega_multi <- matrix(0, J, J)
markup_multi <- compute_markup(own_elas_jt, cross_elas_jt, Omega_multi, is_Multi=TRUE)
markup_multi_med <- markup_multi |>
  select(Brand, descrip, markup, markup_dev_p, mc) |>
  group_by(Brand, descrip) |>
  summarize(markup = median(markup), markup_dev_p = median(markup_dev_p), 
            mc = median(mc), .groups = 'drop')

# joint pricing of all brands
J <- nrow(cross_elas_df)
Omega_joint <- matrix(1, nrow = J, ncol = J)
markup_joint <- compute_markup(own_elas_jt, cross_elas_jt, Omega_joint)
markup_joint_med <- markup_joint |>
  select(Brand, descrip, markup, markup_dev_p, mc) |>
  group_by(Brand, descrip) |>
  summarize(markup = median(markup), markup_dev_p = median(markup_dev_p), 
            mc = median(mc), .groups = 'drop')

res_markup <- left_join(markup_sin_med |> select(Brand, descrip, markup, markup_dev_p),
                        markup_multi_med |> select(Brand, descrip, markup, markup_dev_p),
                        by = c("Brand", "descrip")) |>
                left_join(markup_joint_med |> select(Brand, descrip, markup, markup_dev_p),
                          by = c("Brand", "descrip"), suffix = c(".multi", ".joint"))

res_markup <- res_markup %>%
  knitr::kable(format = "latex", booktabs = TRUE, caption = "Estimated markup") %>%
  kableExtra::kable_styling(latex_options = "hold_position")
cat(res_markup)
```

## Answer to Q6
```{r echo=TRUE, include=TRUE}
res_mc <- left_join(markup_sin_med |> select(Brand, descrip, mc),
                        markup_multi_med |> select(Brand, descrip, mc),
                        by = c("Brand", "descrip")) |>
                left_join(markup_joint_med |> select(Brand, descrip, mc),
                          by = c("Brand", "descrip"), suffix = c(".multi", ".joint"))

res_mc <- res_mc %>%
  knitr::kable(format = "latex", booktabs = TRUE, caption = "Estimated markup") %>%
  kableExtra::kable_styling(latex_options = "hold_position")
cat(res_mc)
```
## Setup function for Q7
```{r echo=TRUE, include=TRUE}
compute_price_eq = function(df, init_p, owner_mat, alpha_hat, beta_hat, is_Multi =TRUE){
  
  # iteration stop parameters
  epsilon <- 1e-5
  df$price <- init_p
  error <- 10000
  count_max <- 20
  counter <- 0
  
  while (error > epsilon & counter < count_max) {
    # check counter
    counter = counter + 1
    print(counter)
    print(error)
    
    unique_week <- unique(df$week)
    unique_store <- unique(df$store)
    
    market_comb <- expand.grid(week = unique_week, store = unique_store)
    
    # store list of p
    p_k_list <- vector("list", nrow(market_comb))
    
    # calc eta_(p) for each market
    for (i in 1:nrow(market_comb)) {
      
      week_i <- market_comb$week[i]
      store_i <- market_comb$store[i]
      
      # subset of a particular market
      df_t <- df |> filter(week == week_i & store == store_i)
      
      # compute own elasticity for each market
      sub_own_elas <- df_t |>
        select(week, store, upc, descrip, price, move, s_jt, Brand, mc) |>
        mutate(own_elas = alpha_hat * price * (1 - s_jt)) 
      
      # compute cross elasticity for each market
      sub_cross_elas <- df_t |>
        select(week, store, upc, descrip, price, move, s_jt, Brand, mc) |>
        mutate(cross_elas = (-1) * alpha_hat * price * s_jt)
      
      # number of product
      J <- nrow(sub_cross_elas)
      
      # if multi-product bertrand nash
      if (is_Multi) {
        for (j in 1:J) {
          for (k in 1:J) {
            # if j's brand is equal to k's brand, take 1 
            if (sub_cross_elas$Brand[j] == sub_cross_elas$Brand[k]){
              owner_mat[j,k] = 1
            }
          }
        }
      }
      
      # calculate elasticity matrix
      elas_mat <- matrix(rep(sub_cross_elas$cross_elas, J), nrow = J, ncol = J)
      diag(elas_mat) <- sub_own_elas$own_elas
      
      # calculate matrix S(p)
      price_mat <- matrix(rep((1/sub_cross_elas$price), J), nrow = J, ncol = J)
      share_mat <- t(matrix(rep(sub_cross_elas$s_jt, J), nrow = J, ncol = J))
      S_p_mat <- (-1) * elas_mat * price_mat * share_mat
      
      # calculate p_k for a paticular market
      D_p_mat <- owner_mat * S_p_mat
      p_k <- sub_cross_elas$mc + solve(D_p_mat) %*% sub_cross_elas$s_jt
      
      # calculate new share
      X_j <- as.matrix(df_t[, grepl("dummy_", colnames(df_t))])
      xi_hat <- log(df_t$s_jt/df_t$s_0t) - (alpha_hat * df_t$price + X_j %*% beta_hat)
      numerator <- exp(alpha_hat * p_k + X_j %*% beta_hat + xi_hat)
      s_jt_old <- df$s_jt
      s_jt <- numerator / (1 + sum(numerator))
      
      # to dataframe 
      market_df <- data.frame(week = market_comb$week[i],
                              store = market_comb$store[i],
                              upc = sub_cross_elas$upc,
                              s_jt_post = s_jt,
                              price_post = p_k)
      # store dataframe
      p_k_list[[i]] <- market_df
    }
    return_df <- do.call(rbind, p_k_list)
    
    #update
    error <- max(abs(return_df$price_post - df$price))
    df$price <- return_df$price_post
    df$s_jt <- return_df$s_jt_post
  }
  return(return_df)
}
```

## Answer to Q7
```{r echo=TRUE, include=TRUE}
# compute price equilibrium for counterfactural exercise
df <- left_join(df, markup_multi |> select(store, week, upc, mc),
                by = c("store", "week", "upc"))

# initial price
init_p <- rep(0.02, nrow(df))

# computation result
alpha_hat <- model1_IV$coefficients["fit_price"]
beta_hat <- as.vector(model1_IV$coefficients)[3:11]
df <- df |> mutate(mc_post = mc * 1.1)# add 10% increase
p_eq_ct <- df %>%
  mutate(mc = mc_post) %>% # set marginal cost 10% increase
  compute_price_eq(., init_p, Omega_multi, alpha_hat, beta_hat)

# join result
df <- left_join(df, p_eq_ct, c("store", "week", "upc")) |>
  mutate(price_pre = price)

# results to tex
res_p_eq_ct <- df |>
  select(Brand, descrip, price_pre, price_post, mc, mc_post) |>
  group_by(Brand, descrip) |>
  summarize(price_pre = median(price_pre),
            price_post = median(price_post), 
            mc_price_share_diff = median((mc_post - mc)/price_post),
            .groups = 'drop') |>
  knitr::kable(format = "latex", booktabs = TRUE, 
               caption = "Counterfactural Exercise (MC increases by 10%)") |>
  kableExtra::kable_styling(latex_options = "hold_position")
cat(res_p_eq_ct)
```
## Setup function for Q8
```{r echo=TRUE, include=TRUE}
compute_walfare = function(df, alpha_hat, beta_hat){
  
    unique_week <- unique(df$week)
    unique_store <- unique(df$store)
    
    # market list
    market_comb <- expand.grid(week = unique_week, store = unique_store)
    
    # store list of p
    walfare_list <- vector("list", nrow(market_comb))
    
    # calculating walfare for each market
    for (i in 1:nrow(market_comb)) {
      week_i <- market_comb$week[i]
      store_i <- market_comb$store[i]
      
      # subset of a particular market
      df_t <- df |> filter(week == week_i & store == store_i)
      
      # matrix X_j
      X_j <- as.matrix(df_t[, grepl("dummy_", colnames(df_t))])
      
      # calculate pre delta_jt
      xi_hat <- log(df_t$s_jt_old/df_t$s_0t) - (alpha_hat * df_t$price_old + X_j %*% beta_hat)
      delta<- alpha_hat * df_t$price + X_j %*% beta_hat + xi_hat
      
      # caliculate CV based on Small and Rosen (1981)
      #CV <- (1 / (-1) * alpha_hat) * (1+log(sum(exp(delta_post))) - (1+ log(sum(exp(delta_pre)))))
      CS <- 1+log(sum(exp(delta)))
      
      # calculate producer surplus for each brand in a paticular market
      M_t <- mean(df_t$custcoun)
      PS_f_t <- df_t |>
        mutate(calc_profit = (price - mc) * s_jt * M_t) |>
        group_by(Brand, week, store) |>
        summarize(calc_profit = sum(calc_profit), .groups = 'drop')
      
      # summation accross firm in the market
      PS  <-  PS_f_t |>
        summarize(calc_profit = sum(calc_profit), .groups = 'drop')
      
      # to dataframe 
      walfare_df <- data.frame(week = week_i,
                               store = store_i,
                               CS = CS,
                               PS = PS$calc_profit,
                               TS = CS + PS$calc_profit)
      
      # store dataframe
      walfare_list[[i]] <- walfare_df
    }
    return_df <- do.call(rbind, walfare_list)
    return(return_df)
}
```

## Answer to Q8
```{r echo=TRUE, include=TRUE}
# walfare in pre counter factural exercise
walfare_pre <- df |>
  mutate(price_old = price, s_jt_old = s_jt) |> # set variables for xi
  compute_walfare(alpha_hat, beta_hat)

# walfare in counter factural exercise
walfare_post <- df |>
  mutate(price_old = price, s_jt_old = s_jt,
         price = price_post, mc = mc_post, s_jt = s_jt_post) |> # use updated variables
  compute_walfare(alpha_hat, beta_hat)

# take difference of each surplus
Diff_CS <- walfare_post$CS - walfare_pre$CS
Diff_PS <- walfare_post$PS - walfare_pre$PS
Diff_TS <- walfare_post$TS - walfare_pre$TS

# results to tex
res_walfare <- walfare_post |>
  mutate(Diff_CS = Diff_CS, Diff_PS = Diff_PS, Diff_TS = Diff_TS) |>
  select(week, store, Diff_CS, Diff_PS, Diff_TS) |>
  summarize(sum_Diff_CS = sum(Diff_CS), sum_Diff_PS = sum(Diff_PS), sum_Diff_TS = sum(Diff_TS), 
            mean_Diff_CS = mean(Diff_CS), mean_Diff_PS = mean(Diff_PS), mean_Diff_TS = mean(Diff_TS), 
            .groups = 'drop') |>
  knitr::kable(format = "latex", booktabs = TRUE, 
               caption = "Summary of each surplus difference") |>
  kableExtra::kable_styling(latex_options = "hold_position")
cat(res_walfare)
```

## Answer to Q9
```{r echo=TRUE, include=TRUE}
### Q9 Answer ###

# set merged brand code 99999
## Note: Ownership matrix is automatically calculated based on merged brand code in this function
df <- df %>%
  mutate(Brand_merged = if_else(Brand %in% c(12000, 49000), 99999, Brand))


res_merged <- df %>%
  mutate(Brand = Brand_merged) %>% # set merged brand code
  compute_price_eq(., init_p, Omega_multi, alpha_hat, beta_hat) %>%
  rename(price_merged = price_post)

# join result
df <- left_join(df, res_merged, c("store", "week", "upc")) |>
  mutate(price_pre = price)

res_merged <- df |>
  select(Brand, Brand_merged,  descrip, price_pre, price_merged) |>
  group_by(Brand, Brand_merged,  descrip) |>
  summarize(price_pre = median(price_pre),
            price_merged = median(price_merged),
            .groups = 'drop') |>
  knitr::kable(format = "latex", booktabs = TRUE, 
               caption = "Merge impact on the equilibrium price (median across market)") |>
  kableExtra::kable_styling(latex_options = "hold_position")
cat(res_merged)
```

