---
title: "Appendix: Source code"
output:
  pdf_document:
    latex_engine: pdflatex
    keep_tex: true
  html_document:
    df_print: paged
date: "2024-04-21"
---

```{r setup, include=TRUE, echo=TRUE}
knitr::opts_chunk$set(echo = TRUE)
rm(list = ls())
gc()
set.seed(1)
options(digits=6) 
if (!require("pacman")) install.packages("pacman")
pacman::p_load(
  plm,
  ggplot2,
  tidyverse,
  fixest,
  knitr,
  optimx,
  kableExtra,
  tidymodels,
  modelsummary,
  ggplot2
)
```

### Data
```{r echo=TRUE, include=TRUE}

df <- read_csv("./input/MROZ_mini.csv")
head(df, 30)
```


# Question 1-1
```{r echo=TRUE, include=TRUE}

##### Question 1 #####

const <- rep(1, nrow(df))
Mat_X <- as.matrix(cbind(const, df[, 1]))
Mat_y <- as.matrix(df[, 3])

# Computing beta_hat
analytical_beta <- solve(t(Mat_X) %*% Mat_X) %*% (t(Mat_X) %*% Mat_y) 
```

## Answer to Q1-1
```{r echo=TRUE, include=TRUE}
### Q1 Answer ###
print(paste("beta_0: ", analytical_beta[1]))
print(paste("beta_1: ", analytical_beta[2]))
```

## Result table in Q1-1
```{r echo=TRUE, include=TRUE}
# Create the result table
coefs_Q1_1 <- data.frame(
  variable = c("Constant",  "educ", "Num.Obs."),
  OLS_model = c(format(analytical_beta[1], digits = 4),
               format(analytical_beta[2], digits = 4),
               format(nrow(df), digits = 1))
)

# result the table
coefs_table_Q1_1  <- kable(coefs_Q1_1,
                           format="latex",
                           caption = "Analytical OLS estimation Result",
                           align = c("l", "c"))  %>%
  kable_styling(full_width = FALSE) 
coefs_table_Q1_1 
```

# Question 1-2
```{r echo=TRUE, include=TRUE}
##### Question 2 #####

# Definition of the objective function
compute_ols <- function(theta, df) {
  beta_0 <- theta[1]
  beta_1 <- theta[2]
  J <- 0.0
  for (i in 1:nrow(df)) {
    add_J <- (df$lwage[[i]] - beta_0 - (beta_1*df$educ[[i]]))** 2
    J <- J + add_J
  }
  return(J)
} 

# Set initial value of theta
initial_theta <- c(0, 0)

# Minimizing the objective function by using optim function
result <- optim(par = initial_theta, fn = compute_ols, df = df, method = "BFGS")
result

```

## Answer to Q1-2
```{r echo=TRUE, include=TRUE}
### Q2 Answer ###
print(paste("Analytical beta_0: ", analytical_beta[1]))
print(paste("Numerical beta_0: ", result$par[1]))
print(paste("Analytical beta_1: ", analytical_beta[2]))
print(paste("Numerical beta_1: ", result$par[2]))
```

## Result table in Q1-2
```{r echo=TRUE, include=TRUE}
# Create the result table
coefs_Q1_2 <- data.frame(
  variable = c("Constant",  "educ", "Num.Obs."),
  Analycal_OLS = c(format(analytical_beta[1], digits = 4),
                    format(analytical_beta[2], digits = 4),
                    format(nrow(df), digits = 1)),
  Numerical_OLS = c(format(result$par[1], digits = 4),
                format(result$par[2], digits = 4),
                format(nrow(df), digits = 1))
)

# result table
coefs_table_Q1_2  <- kable(coefs_Q1_2,
                           format="latex",
                           caption = "OLS estimation Result",
                           align = c("l", "c", "c"))  %>%
  kable_styling(full_width = FALSE) 
coefs_table_Q1_2 
```

# Question 1-3
```{r echo=TRUE, include=TRUE}

# compute Asymptotic SE of OLS estimator

# Hayashi p.123 calculating sample mean of S
compute_S_hat <- function(theta, df) {
  S_hat <- matrix(0, ncol = 2, nrow = 2)
  for (i in 1:nrow(df)) {
    x_i_mat <- Mat_X[i, ]
    epsilon_hat <- as.numeric(df$lwage[[i]] - t(x_i_mat) %*% theta)
    add_S_hat <- (epsilon_hat ^ 2) * (x_i_mat %*% t(x_i_mat))
    S_hat <- S_hat + add_S_hat
  }
  S_hat <- (1/nrow(df)) * S_hat
  return(S_hat)
}

S_xx <- (1/nrow(df)) * (t(Mat_X) %*% Mat_X)
S_hat <- compute_S_hat(analytical_beta, df)

# Computing the asymptotic variance estimator
Avar_est <- solve(S_xx) %*% S_hat %*% solve(S_xx)

# Computing the asymptotic SE for beta_0 and beta_1
Asy_std_beta_0 <- sqrt ((1/nrow(df)) * Avar_est[1])
Asy_std_beta_1 <- sqrt ((1/nrow(df)) * Avar_est[4])

```

## Answer to Q1-3
```{r echo=TRUE, include=TRUE}
### Q3 Answer ###
print(paste("Asymptotic standard error beta 0: ", Asy_std_beta_0))
print(paste("Asymptotic standard error beta 1: ", Asy_std_beta_1))
```

## Result table in Q1-3
```{r echo=TRUE, include=TRUE}
# Create the result table
coefs_Q1_3 <- data.frame(
  variable = c("Constant", "",  "educ", "", "Num.Obs."),
  OLS_model = c(format(analytical_beta[1], digits = 4),
               paste("(", format(Asy_std_beta_0, digits = 4), ")"),  
               format(analytical_beta[2], digits = 4), 
               paste("(", format(Asy_std_beta_1, digits = 4), ")"),
               nrow(df))
)

coefs_table_Q1_3  <- kable(coefs_Q1_3,
                           format="latex",
                           caption = "Analytical OLS estimation Result",
                           align = c("l", "c"))  %>%
  kable_styling(full_width = FALSE) 
coefs_table_Q1_3
```

# Question 1-6
```{r echo=TRUE, include=TRUE}
##### Question 6 #####

# Define Z as IV
Mat_Z <- as.matrix(cbind(const, df[, 2])) # const + futheduc

# get IV estimator
P_Z = Mat_Z %*% solve(t(Mat_Z) %*% Mat_Z) %*% t(Mat_Z)
numerical_beta_IV <- solve(t(Mat_X) %*% P_Z %*% Mat_X) %*% (t(Mat_X) %*% P_Z %*% Mat_y)
numerical_beta_IV

# Compute asymptotic SE of IV estimator based on Hansen p. 354

# Compute epsilon_hat
compute_epsilon_hat <- function(theta, df) {
  epsilon_hat <- 0
  for (i in 1:nrow(df)) {
    x_i_mat <- Mat_X[i, ]
    z_i_mat <- Mat_Z[i, ]
    add_epsilon_hat <- as.numeric(df$lwage[[i]] - t(x_i_mat) %*% theta)
    add_epsilon_hat <- (add_epsilon_hat) ^ 2
    epsilon_hat <- epsilon_hat + add_epsilon_hat
  }
  epsilon_hat <- (1/nrow(df)) * epsilon_hat
  return(epsilon_hat)
}

Q_xz <- (1/nrow(df)) * (t(Mat_X) %*% Mat_Z)
Q_zx <- (1/nrow(df)) * (t(Mat_Z) %*% Mat_X)
Q_zz <- (1/nrow(df)) * (t(Mat_Z) %*% Mat_Z)
epsilon_hat <- compute_epsilon_hat(numerical_beta_IV, df)

# Computing the asymptotic variance estimator
edge_comp <- solve(Q_xz %*% solve(Q_zz) %*% Q_zx)
Avar_est_IV <- edge_comp * epsilon_hat

# Computing the asymptotic SE for beta_0 and beta_1
Asy_std_beta_IV_0 <- sqrt ((1/nrow(df)) * Avar_est_IV[1])
Asy_std_beta_IV_1 <- sqrt ((1/nrow(df)) * Avar_est_IV[4])

```

## Answer to Q1-6
```{r echo=TRUE, include=TRUE}
### Q3 Answer ###
print(paste("Numerical beta_IV_0: ", numerical_beta_IV[1]))
print(paste("Numerical beta_IV_1: ", numerical_beta_IV[2]))
print(paste("Asymptotic standard error beta IV 0: ", Asy_std_beta_IV_0))
print(paste("Asymptotic standard error beta IV 1: ", Asy_std_beta_IV_1))
```

## Result table in Q1-6
```{r echo=TRUE, include=TRUE}
coefs_Q1_6 <- data.frame(
  variable = c("Constant", "",  "educ", "", "Num.Obs."),
  OLS_model = c(format(analytical_beta[1], digits = 4),
             paste("(", format(Asy_std_beta_0, digits = 4), ")"),  
             format(analytical_beta[2], digits = 4), 
             paste("(", format(Asy_std_beta_1, digits = 4), ")"),
             nrow(df)),
  IV_model = c(format(numerical_beta_IV[1], digits = 4),
            paste("(", format(Asy_std_beta_IV_0, digits = 4), ")"),  
            format(numerical_beta_IV[2], digits = 4), 
            paste("(", format(Asy_std_beta_IV_1, digits = 4), ")"),
            nrow(df))
)

# result table
coefs_table_Q1_6  <- kable(coefs_Q1_6, 
                           format="latex",
                           caption = "IV estimation Result",
                           align = c("l", "c", "c")) %>%
                     kable_styling(full_width = FALSE) 

coefs_table_Q1_6 
```

### Kinoko Takenoko Data
```{r echo=TRUE, include=TRUE}
kntk_df <- read_csv("./input/data_KinokoTakenoko.csv")

# Set price
kntk_df <- kntk_df %>%
    mutate(p_kino = if_else(occasion == "X1", 200, 0),
           p_kino = if_else(occasion == "X2", 170, p_kino),
           p_kino = if_else(occasion == "X3", 240, p_kino),
           p_kino = if_else(occasion == "X4", 200, p_kino),
           p_kino = if_else(occasion == "X5", 200, p_kino),
           p_take = if_else(occasion == "X1", 200, 0),
           p_take = if_else(occasion == "X2", 200, p_take),
           p_take = if_else(occasion == "X3", 200, p_take),
           p_take = if_else(occasion == "X4", 250, p_take),
           p_take = if_else(occasion == "X5", 180, p_take)
           )

head(kntk_df, 30)
```

# Question 2-4
```{r echo=TRUE, include=TRUE}
##### Question 2-4 #####
compute_loglikelihood <- function(theta, df) {
  alpha_kino <- theta[1]
  alpha_take <- theta[2]
  beta <- theta[3]
  
  # Calculate probability for i, j, k
  df <- df %>%
    mutate(denominator = 1 + exp(alpha_kino - beta*p_kino) + exp(alpha_take - beta*p_take),
           prob = if_else(choice == 1, exp(alpha_kino - beta*p_kino) / denominator, 0),
           prob = if_else(choice == 2, exp(alpha_take - beta*p_take) / denominator, prob),
           prob = if_else(choice == 0, 1 / denominator, prob))

  N = max(df$id)
  lf <- 0.0
  for (i in 1:N) {
    for (k in 1:5) {
      # get P_{ijk}
      prob <- df %>%
        filter(id == i & occasion == paste0("X", k)) %>%
        pull(prob)
      
      add_lf <- log(prob)
      
      lf <- lf + add_lf
    }
  }
  return(lf)
} 

# OLS To get the initial value
reg_df <- kntk_df %>% 
  mutate(y = if_else(choice == 1, 1, 0), 
         x = if_else(choice == 1, p_kino, 0),
         x = if_else(choice == 2, p_take, x))
model <- feols(y ~  1   + x, 
               reg_df, vcov="White"
)
etable(model)

# Maximizing the Log-Likelihood by using optim function
initial_theta <- c(model$coefficients[1], model$coefficients[1], model$coefficients[2])
start.time <- Sys.time()
MLE_res <- optim(par = initial_theta, fn = compute_loglikelihood, df = kntk_df, method='BFGS', control = list(fnscale = -1))
end.time <- Sys.time()
end.time - start.time
```

## Answer to Q2-4
```{r echo=TRUE, include=TRUE}
#Answer Q2-4
MLE_res
print(paste("alpha kinoko hat: ", MLE_res$par[1]))
print(paste("alpha takenoko hat: ", MLE_res$par[2]))
print(paste("beta: ", MLE_res$par[3]))
```

## Result table in Q2-4
```{r echo=TRUE, include=TRUE}
# Create result table
coefs_Q2_4 <- data.frame(
  variable = c("alpha kinoko",  "alpha takenoko", "beta", "Num.Obs."),
  estimates = c(format(MLE_res$par[1], digits = 4),
                   format(MLE_res$par[2], digits = 4),
                   format(MLE_res$par[3], digits = 4),
                   format(nrow(kntk_df), digits = 1))
)

# result table
coefs_table_Q2_4  <- kable(coefs_Q2_4,
                           format="latex",
                           caption = "Estimation Result",
                           align = c("l", "c"))  %>%
  kable_styling(full_width = FALSE) 
coefs_table_Q2_4
```

## Robustness check about initial value
```{r echo=TRUE, include=TRUE}
for (i in seq(from = 0, to = 0.5, by = 0.5)) {
  initial_theta <- c(i, i, i)
  print(paste("Initial theta: ", c(i, i, i)))
  start.time <- Sys.time()
  MLE_res <- optim(par = initial_theta, fn = compute_loglikelihood, df = kntk_df, method='BFGS', control = list(fnscale = -1))
  end.time <- Sys.time()
  end.time - start.time
  print(MLE_res)
}
```


# Question 3-2
```{r echo=TRUE, include=TRUE}
##### Question 3-2 #####
set.seed(0)
mu <- 2
sigma <- sqrt(2)
R <- 1000

# Define Monte Carlo simulation function
compute_E_X2_hat <- function(R) {
  nu_vec <- rnorm(R, 0, 1) # fixed by seed

  E_X2_hat = 0
  for (nu_r in nu_vec) {
    E_X2_hat = E_X2_hat + (mu + sigma * nu_r)^2
  }
  
  E_X2_hat <- (1/ R) *  E_X2_hat
  return(E_X2_hat)
} 
```

## Answer to Q2-4
```{r echo=TRUE, include=TRUE}
##### Answer Q3-2 #####
res_E_X2_hat <- compute_E_X2_hat(R)
print(paste("estimated E[X^2]: ", res_E_X2_hat))
```

## Result table in Q2-4
```{r echo=TRUE, include=TRUE}
# Create result table
coefs_Q3_2 <- data.frame(
  variable = c("E[X^2]",  "R"),
  estimates = c(format(res_E_X2_hat, digits = 6),
                format(R, digits = 1))
)

coefs_table_Q3_2  <- kable(coefs_Q3_2,
                           format="latex",
                           caption = "Estimation Result when R = 1000",
                           align = c("l", "c"))  %>%
  kable_styling(full_width = FALSE) 
coefs_table_Q3_2
```

### Answer to Question 3-2: Graph Part
```{r echo=TRUE, include=TRUE}
# check dependency on the number of R
res_df = data.frame(matrix(ncol = 2, nrow = 0))
colnames(res_df) <- c("R", "estimated_E_X2")

i = 0
for (r in seq(from = 100, to = 50000, by = 100)) {
  i = i + 1
  
  res_E_X2_hat_r <- compute_E_X2_hat(r)
  
  # Store result
  res_df[i, 1] <- r
  res_df[i, 2] <- res_E_X2_hat_r
}

# Plot R and estimates
ggplot(res_df, aes(x = R, y = estimated_E_X2)) +
  geom_point() +
  labs(x = "R", y = "estimated_E_X2") +
  theme_minimal()
ggsave("./figure/Q3_2_MC.pdf", device = "pdf")
```

```{r echo=TRUE, include=TRUE}
data <- read.csv("./input/data_KinokoTakenoko.csv")

alphaK <- 1
alphaT <- 1
beta <- 0.01
f_logit_prob <- function(alphaK, alphaT, beta, priceK, priceT){
UK <- alphaK - beta*priceK
UT <- alphaT - beta*priceT
probK <- exp(UK)/(1+exp(UK)+exp(UT))
probT <- exp(UT)/(1+exp(UK)+exp(UT))
prob0 <- 1 - (probK + probT)
return( cbind(probK, probT, prob0))
}
f_likelihood_logit <- function(param, data){
alphaK <- param[1]
alphaT <- param[2]
beta <- param[3]
P1 <- f_logit_prob(alphaK, alphaT, beta, 200, 200)
P2 <- f_logit_prob(alphaK, alphaT, beta, 170, 200)
P3 <- f_logit_prob(alphaK, alphaT, beta, 240, 200)
P4 <- f_logit_prob(alphaK, alphaT, beta, 200, 250)
P5 <- f_logit_prob(alphaK, alphaT, beta, 200, 180)
pred <- rbind(P1, P2, P3, P4, P5)
pred <- as_tibble(pred)
pred$occasion <- c("X1", "X2", "X3", "X4", "X5")
data %>%
left_join(pred, by = "occasion") %>%
mutate( choice_prob = case_when( choice == 0 ~ prob0,
choice == 1 ~ probK,
choice == 2 ~ probT) ) %>%

mutate(log_choice_prob = log(choice_prob)) %>%
select(log_choice_prob) -> result
likelihood <- sum(result)
return(likelihood)
}
ini <- c(5,5, 0.01)
result <- optimx( ini, f_likelihood_logit, data = data, control = list(fnscale=-1), hessian = TRUE)

Hessian <- gHgen(par = as.numeric(result[2,1:3]), f_likelihood_logit, data = data)
print("Estimates")
```